### ISSUE TITLE
Access denied when attempting to copy the snapshot from S3

### ISSUE THREAD

**Issue by aldredb** [satsuma-xyz/node-snapshots#12]
Tried executing the following:

```
sudo ./launcher.sh -c eth_geth_full -d data
```

On this command `aws s3 ls s3://satsuma-snapshots/eth/geth_full/v1.10.23/`, access denied error is output:

`An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied`

Kindly configure the bucket policy to allow public access and the s3 command to use `--request-payer` argument

You can refer to this : https://stackoverflow.com/questions/65760073/how-to-allow-everyone-read-access-to-s3-bucket-as-long-as-requester-pays

**Comment by brianluong** [comment]
Thanks for the heads up, @aldredb! We fixed our bucket and added the `--request-payer` argument [here](https://github.com/satsuma-xyz/node-snapshots/pull/14). Let us know if it works!

**Comment by aldredb** [comment]
@brianluong you need to add `--request-payer requester` in the `aws s3 cp` command too :)

**Comment by brianluong** [comment]
@aldredb Ah, nice catch. Try now?

**Comment by aldredb** [comment]
@brianluong thanks. working now. closing this issue

**Comment by brianluong** [comment]
I'm not sure, we haven't tested it with that version yet.

**Comment by aldredb** [comment]
The time to download and extract is approximately 6 hours, which is quite far from the benchmark stated in the repo (78min). Initially I used a different OS, but the same occurred when I followed the pre-requisites (OS, instance size, etc) in the repository. Copy-pasting the copy progress below. I too [configured](https://awscli.amazonaws.com/v2/documentation/api/latest/topic/s3-config.html#configuration-values) AWS S3 CLI to download faster but the bottleneck is not in the download speed

```
aws s3 cp --request-payer requester s3://satsuma-snapshots/eth/geth_full/v1.10.23/geth_full_1670947203.tar.zstd -
+ pv
+ /zstd/zstd --long=31 -d
+ tar -xf -
924GiB 6:17:23 [41.8MiB/s] 
…
Downloaded snapshot and launched docker container in 22653 seconds.
```

If I'm just copying the the snapshot without funneling to `ztsd`, I'm able to get ~150MBps by  setting `max_concurrent_requests` to 50 and `multipart_chunksize` to 256MB

**Comment by dianwen** [comment]
Hey @aldredb! One thing to check is that you're running zstd version > 1.5.0 since versions before that have significantly worse performance.

We haven't provisioned a geth full node in a while but will let you know how long it takes next time we do so. It's possible this is out of date / inaccurate in some way.

**Comment by aldredb** [comment]
@dianwen yep i'm running `zstd` version 1.5.2
